import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DarkHeader from "./components/dark-header";
import Carausel from "./components/caraousel";
import Editors from "./components/editorspick";
import GreenDiv from "./components/green-div";
import LightHeader from "./components/lightheader";
import ProductCard from "./components/products-card";
import Fluid from "./components/fluid";
import Footer from "./components/footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "E -Commerce Store by AkazBaba",
  description: "Generated by AkazBaba",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DarkHeader />
        <LightHeader />
         {children}
         <Carausel />
         <Fluid/>
         <Editors/>
         <GreenDiv/>
         <ProductCard/>
         <Footer/>
      </body>
    </html>
  );
}
